#!/usr/bin/env bash

# Run this to change githook config directory to a custom location handled by VCS:
# git config core.hooksPath .githooks

# If you have trouble, try making sure the file is marked as executable:
# chmod +x <filename>

LC_ALL=C

local_branch="$(git rev-parse --abbrev-ref HEAD)"

# valid_branch_regex="^(main)|(develop)|(beta)|(feature|bugfix|improvement|library|prerelease|release|hotfix|lts)\/[a-z0-9._-]+$"

valid_branch_regex="^(main)|(develop)|(beta)|lts\/\d*\.(\d*|x)\.(\d*|x)|(feature|bugfix|improvement|library|prerelease|release|hotfix|lts)\/[a-z0-9._-]+$"

message="There is something wrong with your branch name. Branch names in this project must adhere to this contract: $valid_branch_regex. Your commit will be rejected. You should rename your branch to a valid name and try again."

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo "$message"
    exit 1
fi

exit 0