---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  workflow_dispatch:

  push:
    branches-ignore: [main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [main]

#env:

  # tflint_azurerm_uri: "https://github.com/terraform-linters/tflint-ruleset-azurerm/releases/download/v0.9.0/tflint-ruleset-azurerm_linux_amd64.zip"

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Add any plugins to the linters
      # - name: Download tflint AzureRM plugin
      #   run: |
      #     pwd
      #     wget $tflint_azurerm_uri
      #     mkdir ./.tflint.d/
      #     mkdir ./.tflint.d/plugins/
      #     unzip tflint-ruleset-azurerm_linux_amd64.zip -d ./.tflint.d/plugins/
      #     chmod +x ./.tflint.d/plugins/tflint-ruleset-azurerm

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v3.16.1
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_MARKDOWN: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}